#!/bin/bash
docker exec part1-r1-1 apt -y install curl
docker exec part1-r1-1 apt -y install gnupg
docker exec part1-r1-1 curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
docker exec part1-r1-1 apt install lsb-release
docker exec part1-r1-1 FRRVER=frr-stable
docker exec part1-r1-1 echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list
docker exec part1-r1-1 apt update && apt -y install frr frr-pythontools
docker cp daemons part1-r1-1/etc/frr/
docker exec part1-r1-1 service frr restart
docker exec part1-r1-1 vtysh -c 'configure terminal' -c 'router ospf' -c 'network 10.0.14.0/24 area 0.0.0.0' -c 'network 10.0.16.0/24 area 0.0.0.0' -c 'network 10.0.18.0/24 area 0.0.0.0' -c 'end'
docker exec part1-r1-1 vtysh -c 'configure terminal' -c 'interface eth0' -c 'ip ospf cost 5' -c 'exit' -c 'end'
docker exec part1-r1-1 vtysh -c 'configure terminal' -c 'interface eth1' -c 'ip ospf cost 5' -c 'exit' -c 'end'
docker exec part1-r1-1 vtysh -c 'configure terminal' -c 'interface eth2' -c 'ip ospf cost 5' -c 'exit' -c 'end'


docker exec part1-r2-1 apt -y install curl
docker exec part1-r2-1 apt -y install gnupg
docker exec part1-r2-1 curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
docker exec part1-r2-1 apt install lsb-release
docker exec part1-r2-1 FRRVER=frr-stable
docker exec part1-r2-1 echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list
docker exec part1-r2-1 apt update && apt -y install frr frr-pythontools
docker cp daemons part1-r2-1/etc/frr/
docker exec part1-r2-1 service frr restart
docker exec part1-r2-1 vtysh -c 'configure terminal' -c 'router ospf' -c 'network 10.0.16.0/24 area 0.0.0.0' -c 'network 10.0.17.0/24 area 0.0.0.0' -c 'end'
docker exec part1-r2-1 vtysh -c 'configure terminal' -c 'interface eth0' -c 'ip ospf cost 5' -c 'exit' -c 'end'
docker exec part1-r2-1 vtysh -c 'configure terminal' -c 'interface eth1' -c 'ip ospf cost 5' -c 'exit' -c 'end'


docker exec part1-r3-1 apt -y install curl
docker exec part1-r3-1 apt -y install gnupg
docker exec part1-r3-1 curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
docker exec part1-r3-1 apt install lsb-release
docker exec part1-r3-1 FRRVER=frr-stable
docker exec part1-r3-1 echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list
docker exec part1-r3-1 apt update && apt -y install frr frr-pythontools
docker cp daemons part1-r3-1/etc/frr/
docker exec part1-r3-1 service frr restart
docker exec part1-r3-1 vtysh -c 'configure terminal' -c 'router ospf' -c 'network 10.0.15.0/24 area 0.0.0.0' -c 'network 10.0.18.0/24 area 0.0.0.0' -c 'network 10.0.19.0/24 area 0.0.0.0' -c 'end'
docker exec part1-r3-1 vtysh -c 'configure terminal' -c 'interface eth0' -c 'ip ospf cost 5' -c 'exit' -c 'end'
docker exec part1-r3-1 vtysh -c 'configure terminal' -c 'interface eth1' -c 'ip ospf cost 5' -c 'exit' -c 'end'
docker exec part1-r3-1 vtysh -c 'configure terminal' -c 'interface eth2' -c 'ip ospf cost 5' -c 'exit' -c 'end'

docker exec part1-r4-1 apt -y install curl
docker exec part1-r4-1 apt -y install gnupg
docker exec part1-r4-1 curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
docker exec part1-r4-1 apt install lsb-release
docker exec part1-r4-1 FRRVER=frr-stable
docker exec part1-r4-1 echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list
docker exec part1-r4-1 apt update && apt -y install frr frr-pythontools
docker cp daemons part1-r4-1/etc/frr/
docker exec part1-r4-1 service frr restart
docker exec part1-r4-1 vtysh -c 'configure terminal' -c 'router ospf' -c 'network 10.0.16.0/24 area 0.0.0.0' -c 'network 10.0.17.0/24 area 0.0.0.0' -c 'end'
docker exec part1-r4-1 vtysh -c 'configure terminal' -c 'interface eth0' -c 'ip ospf cost 10' -c 'exit' -c 'end'
docker exec part1-r4-1 vtysh -c 'configure terminal' -c 'interface eth1' -c 'ip ospf cost 5' -c 'exit' -c 'end'

docker exec part1-ha-1 route add -net 10.0.15.0/24 gw 10.0.14.10
docker exec part1-hb-1 route add -net 10.0.14.0/24 gw 10.0.15.3